apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: healthhub
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: healthhub
  DB_USER: postgres
  PORT: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthhub-backend
  namespace: healthhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthhub-backend
  template:
    metadata:
      labels:
        app: healthhub-backend
    spec:
      containers:
      - name: backend
        image: healthhub-backend:latest

        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: healthhub
spec:
  selector:
    app: healthhub-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP