build:
  name: Build Docker Images
  needs: test
  runs-on: ubuntu-latest
  if: github.event_name == 'push'
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # ✅ Place the DockerHub login step here
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # 🧱 Build and push backend image
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/healthhub-backend:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/healthhub-backend:latest
    
    # 🧱 Build and push frontend image
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/healthhub-frontend:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/healthhub-frontend:latest
